# Generated by Django 4.0.4 on 2022-05-26 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_product_file_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
